# Generated by Django 3.0 on 2019-12-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tv',
            old_name='nome',
            new_name='name',
        ),
    ]
