# Generated by Django 3.0 on 2019-12-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_auto_20191205_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tv',
            old_name='grupo',
            new_name='group',
        ),
    ]
