# Generated by Django 3.0 on 2019-12-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0003_auto_20191205_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tv',
            options={'ordering': ['name'], 'verbose_name': 'Televisão', 'verbose_name_plural': 'Televisões'},
        ),
    ]
