# Generated by Django 2.2.7 on 2019-12-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvalidToken',
        ),
    ]
