# Generated by Django 3.0 on 2019-12-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('duration', models.DurationField(verbose_name='Duração')),
                ('order', models.PositiveIntegerField(verbose_name='Ordem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('source', models.FileField(upload_to='content/media/', verbose_name='Arquivo')),
                ('ftype', models.CharField(choices=[('mp4', 'video/mp4'), ('mkv', 'video/webm'), ('ogg', 'video/ogg'), ('gif', 'image/gif'), ('jpg', 'image/jpg'), ('png', 'image/png')], max_length=3, verbose_name='Tipo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('contents', models.ManyToManyField(related_name='groups', through='content.Content', to='content.Media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='content',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_contents', to='content.Group'),
        ),
        migrations.AddField(
            model_name='content',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='content.Media'),
        ),
    ]
