# Generated by Django 3.0 on 2019-12-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='nome',
            new_name='name',
        ),
    ]
