# Generated by Django 3.0 on 2019-12-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20191205_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='ftype',
            field=models.CharField(choices=[('mp4', 'video/mp4'), ('mkv', 'video/webm'), ('ogg', 'video/ogg'), ('gif', 'image/gif'), ('jpg', 'image/jpg'), ('jpeg', 'image/jpeg'), ('png', 'image/png')], max_length=4, verbose_name='Tipo'),
        ),
    ]
