# Generated by Django 2.2.7 on 2019-12-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20191205_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='ftype',
            field=models.CharField(choices=[('video/mp4', 'mp4'), ('video/webm', 'webm'), ('video/ogg', 'ogg'), ('image/gif', 'gif'), ('image/jpg', 'jpg'), ('image/jpeg', 'jpeg'), ('image/png', 'png')], max_length=10, verbose_name='Tipo'),
        ),
    ]
